name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  testWithCommit: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          postman_api_key: ${{ secrets.postmanApiKey }}
          postman_target_workspace_id: 87bf7eea-3c86-4e3c-8888-0e7901d31727
          postman_timeout: 30000